name: Build, Push to Google Artifact Registry, and Deploy to Cloud Run

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env: # Define environment variables here
      GCP_PROJECT_NAME: flask-web-curriculum
      ARTIFACT_REPO_NAME: flask-app-registry
      IMAGE_NAME: flask_app_image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GCP Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_NAME/$ARTIFACT_REPO_NAME/$IMAGE_NAME:latest .

    - name: Push Docker image to Google Artifact Registry
      run: docker push us-central1-docker.pkg.dev/$GCP_PROJECT_NAME/$ARTIFACT_REPO_NAME/$IMAGE_NAME:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy flask-web-app \
          --image us-central1-docker.pkg.dev/$GCP_PROJECT_NAME/$ARTIFACT_REPO_NAME/$IMAGE_NAME:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --ingress all
